import 'dart:async';

import 'package:dartssh2/dartssh2.dart';
import 'package:helm/core/constants/app_constants.dart';
import 'package:helm/core/utils/logger.dart';
import 'package:helm/features/connection/domain/connection_profile.dart';

/// Result of a successful SSH connect + shell open operation.
class SSHConnectionResult {
  const SSHConnectionResult({required this.client, required this.session});

  final SSHClient client;
  final SSHSession session;
}

/// Wraps dartssh2 to provide higher-level connect / shell / disconnect operations.
class SSHService {
  static final _log = HelmLogger('SSHService');

  // ── Public API ─────────────────────────────────────────────────────────

  /// Establishes an SSH connection and opens a PTY shell.
  ///
  /// [privateKeyPem] must be the OpenSSH private key PEM previously generated by [SSHKeyService].
  ///
  /// Throws on connection failure, authentication failure, or timeout.
  Future<SSHConnectionResult> connectAndOpenShell(
    ConnectionProfile profile,
    String privateKeyPem, {
    int columns = AppConstants.defaultTerminalColumns,
    int rows = AppConstants.defaultTerminalRows,
  }) async {
    _log.i(
      'Connecting to ${profile.host}:${profile.port} as ${profile.username}',
    );

    final identities = SSHKeyPair.fromPem(privateKeyPem);

    final socket = await SSHSocket.connect(
      profile.host,
      profile.port,
      timeout: const Duration(seconds: 15),
    );

    final client = SSHClient(
      socket,
      username: profile.username,
      identities: identities,
      keepAliveInterval: const Duration(seconds: 30),
      onVerifyHostKey: (host, key) async => true, // Trust all host keys for now
    );

    final session = await client.shell(
      pty: SSHPtyConfig(type: 'xterm-256color', width: columns, height: rows),
    );

    _log.i('Shell opened for ${profile.name}');
    return SSHConnectionResult(client: client, session: session);
  }

  /// Gracefully disconnects the SSH client.
  Future<void> disconnect(SSHClient client) async {
    if (!client.isClosed) {
      _log.i('Disconnecting SSH client');
      client.close();
      await client.done.catchError((_) {}); // ignore close errors
    }
  }

  /// Sends a resize event to the remote PTY.
  void resizeTerminal(
    SSHSession session, {
    required int columns,
    required int rows,
  }) {
    session.resizeTerminal(columns, rows);
  }

  // ── Reconnect with exponential backoff ────────────────────────────────

  /// Attempts to reconnect up to [AppConstants.maxReconnectAttempts] times.
  ///
  /// Returns null if all attempts fail.
  Future<SSHConnectionResult?> reconnect(
    ConnectionProfile profile,
    String privateKeyPem, {
    int columns = AppConstants.defaultTerminalColumns,
    int rows = AppConstants.defaultTerminalRows,
  }) async {
    for (
      var attempt = 0;
      attempt < AppConstants.maxReconnectAttempts;
      attempt++
    ) {
      final delaySeconds = AppConstants.reconnectDelays[attempt];
      _log.w(
        'Reconnect attempt ${attempt + 1}/${AppConstants.maxReconnectAttempts} '
        '(waiting ${delaySeconds}s)',
      );
      await Future.delayed(Duration(seconds: delaySeconds));

      try {
        final result = await connectAndOpenShell(
          profile,
          privateKeyPem,
          columns: columns,
          rows: rows,
        );
        _log.i('Reconnected successfully on attempt ${attempt + 1}');
        return result;
      } catch (e) {
        _log.e('Reconnect attempt ${attempt + 1} failed', e);
      }
    }

    _log.e('All reconnect attempts exhausted');
    return null;
  }

  /// Maps an exception from dartssh2 to a human-readable error message.
  static String describeError(Object error) {
    if (error is SSHAuthError) return 'Authentication failed';
    if (error is SSHError) return 'SSH error: $error';
    return error.toString();
  }
}
